/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f411re.h"
#define PRESSED 0
void delay(void){
	for(uint32_t i=0; i<100000; i++);
}

int main(void)
{
    /* Loop forever */
	//int Button;
	GPIO_Handle_t GPIOLED;
	GPIOLED.pGPIOx= GPIOA;
	GPIOLED.GPIO_Config.GPIO_PinNumber=GPIO_PIN_NUM_5;
	GPIOLED.GPIO_Config.GPIO_PinMode=GPIO_MODE_OUT;
	GPIOLED.GPIO_Config.GPIO_PinOPType=GPIO_NO_PUPD;
	GPIOLED.GPIO_Config.GPIO_PinSpeed=GPIO_OP_SPEED_FAST;
	GPIOLED.GPIO_Config.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&GPIOLED);

	GPIO_Handle_t GPIOButton;
	GPIOButton.pGPIOx= GPIOC;
	GPIOButton.GPIO_Config.GPIO_PinNumber=GPIO_PIN_NUM_13;
	GPIOButton.GPIO_Config.GPIO_PinMode=GPIO_MODE_IN;
	GPIOButton.GPIO_Config.GPIO_PinOPType=GPIO_NO_PUPD;
	GPIOButton.GPIO_Config.GPIO_PinSpeed=GPIO_OP_SPEED_FAST;
	GPIOButton.GPIO_Config.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&GPIOButton);

	for(;;){
		//GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NUM_5);
		if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NUM_13)==PRESSED){
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NUM_5, GPIO_PIN_SET);
		}else{
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NUM_5, GPIO_PIN_RESET);
		}
		//delay();
	}
}
