/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ADC_BASE_ADDRESS 0x40012000UL
#define ADC_CR1_REG_OFFSET 0x04UL
#define ADC_CR1_REG_ADDRESS (ADC_BASE_ADDRESS + ADC_CR1_REG_OFFSET)
#define RCC_BASE_ADDRESS 0x40023800UL
#define RCC_ABP2_ENR_OFFSET 0x44UL
#define RCC_ABP2_ENR_ADDRESS (RCC_BASE_ADDRESS+RCC_ABP2_ENR_OFFSET)
int main(void)
{
    /* Loop forever */
	//First enable the peripheral clock for ADC 1
	uint32_t *pRccAdc = (uint32_t *)RCC_ABP2_ENR_ADDRESS;
	*pRccAdc = *pRccAdc | (1<<8);

	//Now enabling ADC control register scan bit
	uint32_t *pAdcCr1Reg = (uint32_t *)ADC_CR1_REG_ADDRESS;
	*pAdcCr1Reg = *pAdcCr1Reg | (1<<8); //8th Bit is Scan bit
	for(;;);
}
